<?php
require_once('Builder.php');
require_once('LinkListBuilder.php');
require_once('CategoriesBuilder.php');
require_once('RightColumnBuilder.php');
require_once('JokeBuilder.php');
require_once('JokesFromCategoryBuilder.php');
require_once('NewestJokesBuilder.php');
require_once('ChangeJokeBuilder.php');
require_once('ContentFromJokesBuilder.php');
require_once('JokesFromSearchBuilder.php');
require_once('JokesFromUserBuilder.php');
require_once('PageOffsetBoxBuilder.php');
require_once('MessageBuilder.php');